version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: facial-recognition-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: facial_recognition_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: facial-recognition-backend
    depends_on:
      - postgres
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - upload_data:/app/uploads
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: facial-recognition-frontend
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    networks:
      - app-network
    command: npm start -- --host 0.0.0.0

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  upload_data: